app/wechat/models/auth.py
# !/usr/bin/env python
# _*_ coding:utf-8
#  保存用户的教务系统和图书馆的帐号信息


from app import db


class Auth(db.Model):
    __tablename__ = 'auth'

    openid = db.Column(db.String(32), primary_key=True, unique=True,
            nullable = False)
    studentid = db.Column(db.String(20), nullable=True)
    studentpwd = db.Column(db.String(70), nullable=True)
    libraryid = db.Column(db.String(20), nullable=True)
    librarypwd = db.Column(db.String(70), nullable=True)

    def __init__(self, openid, studentid=None, studentpwd=None,
            libraryid=None, librarypwd=None):
        """
        :openid: 微信用户唯一id
        :studentid: 学生教务系统帐号
        :studentpwd: 学生教务系统密码
        :libraryid: 图书馆帐号
        :librarypwd: 图书馆密码
        """
        self.openid = openid
        self.studentid = studentid
        self.studentpwd = studentpwd
        self.libraryid = libraryid
        self.librarypwd = librarypwd

    def __repr__(self):
        return '<openid %r>' % self.openid

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self

app/wechat/models/pushpost.py
from app import db
from datetime import datetime
import bleach
from markdown import markdown
from sqlalchemy import  extract


class Pushtext(db.Model):
    """ 推送文本消息 """
    __tablename__ = 'pushtexts'
    id = db.Column(db.Integer, primary_key=True)
    media_id = db.Column(db.String(64))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    content = db.Column(db.Text)
    create_time = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    to_confirmed = db.Column(db.String(100))
    to_group_id = db.Column(db.Integer, db.ForeignKey('groups.id')) # 所发给的分组

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self


class Pushnews(db.Model):
    __tablename__ = 'pushnews'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.Text)
    #  把markdown原文格式成html存到数据库，而不是访问时在格式
    media_id = db.Column(db.String(64))
    body_html = db.Column(db.Text)
    create_time = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    to_confirmed = db.Column(db.String(100))
    to_group_id = db.Column(db.Integer, db.ForeignKey('groups.id'))


    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self

    @staticmethod
    def on_body_changed(target, value, oldvalue, initiator):
        allow_tags=['a','abbr','acronym','b','blockquote','code', 'em',
                'i','li','ol','pre','strong','ul', 'h1','h2','h3','p','img']
        #  转换markdown为html, 并清洗html标签
        if value is None or (value is ''):
            target.body_html = ''
        else:
            target.body_html=bleach.linkify(bleach.clean(
                markdown(value,output_form='html'),
                tags=allow_tags,strip=True,
                attributes={
                    '*': ['class'],
                    'a': ['href', 'rel'],
                    'img': ['src', 'alt'],#支持<img src …>标签和属性
                    }
                ))

    @staticmethod
    def getdate(self):
       data = db.session.query(extract('month', self.create_time).label('month')).first()
       return data[0]


db.event.listen(Pushnews.body, 'set', Pushnews.on_body_changed)# 当body被修改时触发

app/wechat/models/role.py
# !/usr/bin/env python
# _*_ coding:utf-8

from app import db


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(20), unique = True)

    def __repr__(self):
        return '<id %r>' % self.id

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self

app/wechat/models/user.py
# !/usr/bin/env python
# _*_ coding:utf-8


from app import db
from datetime import datetime
from app.models import registrations


class WechatUser(db.Model):
    __tablename__ = 'wechatusers'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    openid = db.Column(db.String(32), unique=True, nullable=False)
    nickname = db.Column(db.String(32), nullable=True)
    realname = db.Column(db.String(32), nullable=True)
    classname = db.Column(db.String(32), nullable=True)
    sex = db.Column(db.SmallInteger, default=0, nullable=False)
    province = db.Column(db.String(20), nullable=True)
    city = db.Column(db.String(20), nullable=True)
    country = db.Column(db.String(20), nullable=True)
    headimgurl = db.Column(db.String(150), nullable=True)
    regtime = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    user_setting = db.Column(db.String(100))

    user_group = db.relationship('Group', secondary=registrations,
            backref = db.backref('wechatusers', lazy='dynamic'),
            lazy = 'dynamic')

    #  phone_number = db.Column(db.String(32), nullable=True)
    #  eamil = db.Column(db.String(32), nullable=True)

    def __init__(self, openid, nickname=None, realname=None,
            classname = None, sex = None, province = None, city = None,
            country = None, headimgurl = None, regtime = None):
        self.openid = openid
        self.nickname = nickname
        self.realname = realname
        self.classname = classname
        self.sex = sex
        self.province = province
        self.city = city
        self.country = country
        self.headimgurl = headimgurl
        self.regtime = regtime

    def __repr__(self):
        return '<openid %r>' % self.openid

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self

    @staticmethod
    def on_created(target, value, oldvalue, initiator):
        group = Group.query.filter_by(name='全体用户').first()
        if group is None:
            new_group = Group()
            new_group.name = '全体用户'
            new_group.save()
        #  user.user_group.append(new_group)
        target.user_group.append(Group.query.filter_by(name='全体用户').first())

#  数据库on_created事件监听 #  每插入新对象就初始化用户的user_group
db.event.listen(WechatUser.openid, 'set', WechatUser.on_created)


class Group(db.Model):
    __tablename__ = 'groups'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)
    pushnews= db.relationship('Pushnews', backref='to_group')
    pushtext = db.relationship('Pushtext', backref='to_group')

    @staticmethod
    def seed():
        #  XXX  调用这个方法就可以设置Role的默认值了, 这个可以去掉了
        db.session.add_all(map(lambda r:Group(name=r), ['全体用户', '就业信息', '学术报告']))
        db.session.commit()

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self

    def update(self):
        db.session.commit()
        return self

app/wechat/__init__.py
from flask import Blueprint

wechat = Blueprint('wechat', __name__)

from . import views
from .func_plugins import *

app/wechat/views.py
# !/usr/bin env python
# coding:utf-8

import ast, time, json
from os import path
from datetime import datetime
from flask import flash, session, request, render_template, url_for,\
        redirect, abort, current_app, g, jsonify, Markup
from flask_login import login_required, current_user
from sqlalchemy import extract, func
from app import redis, db
from . import wechat
from .response import handle_wechat_response
from .func_plugins import score
from .models import is_user_exists
from .models.user import WechatUser, Group
from .models.pushpost import Pushnews, Pushtext
from .form import GroupForm, NewsForm, TextForm
from .utils import check_wechat_signature, get_jsapi_signature_data,\
        oauth_request, openid_list, init_wechat_sdk

from functools import wraps


def admin_required(f):
    @wraps(f)
    def decorator(*args, **kwargs):
        if current_user.is_administrator():
            return f(*args, **kwargs)
        else:
            abort(403)
    return decorator


@wechat.route('/test')
def test():
    return 'Hi There'


@wechat.route('/', methods=['GET', 'POST'])
@check_wechat_signature
def handle_wechat_request():
    """ 处理微信回复请求 """
    if request.method == 'GET' :
        #  微信接入认证
        return request.args.get('echostr', '')
    else:
        return handle_wechat_response(request.data)


@wechat.route('/auth-score/<openid>', methods=['GET', 'POST'])
def auth_score(openid=None):
    """ 绑定教务系统 """
    if request.method == 'POST':
        studentid = request.form.get('studentid', '')
        studentpwd = request.form.get('studentpwd', '')
        #  根据用户输入的信息, 进行模拟登录
        if studentid and studentpwd and is_user_exists(openid):
            score.get_info(openid, studentid, studentpwd, check_login=True)
            errmsg = 'ok'
        else:
            errmsg = u'学号或密码格式不合法'
        return jsonify({'errmsg': errmsg})
    elif is_user_exists(openid):
        jsapi = get_jsapi_signature_data(request.url)
        jsapi['jsApiList'] = ['hideAllNonBaseMenuItem']
        return render_template('wechat/auth.html',
                title = '微信查成绩',
                desc = "请绑定教务系统",
                username_label = '学号',
                username_label_placeholder = '请输入你的学号',
                password_label_placeholder = '教务系统密码',
                baidu_analyics = current_app.config['BAIDU_ANALYTICS'],
                jsapi = Markup(jsapi)
                )
    else:
        abort(404)


@wechat.route('/auth-score/<openid>/result', methods=['GET'])
def auth_score_result(openid=None):
    """ 查询学号绑定结果 """
    if is_user_exists(openid):
        redis_prefix = 'wechat:user:auth:score:'
        errmsg_cache = redis.get(redis_prefix + openid)
        errmsg = errmsg_cache.decode()
        if errmsg:
            #  redis.delete(redis_prefix + openid)
            return jsonify({'errmsg' : errmsg})
        else:
            abort(404)
    else:
        abort(404)


@wechat.route('/score-report/<openid>', methods=['GET', 'POST'])
def school_report_card(openid=None):
    """ 学生成绩单 """
    if is_user_exists(openid):
        jsapi = get_jsapi_signature_data(request.url)
        jsapi['jsApiList'] = ['onMenuShareTimeline',
                'onMenuShareAppMessage',
                'onMenuShareQQ',
                'onMenuShareWeibo',
                'onMenuShareQZone']
        score_cache = redis.hgetall('wechat:user:scoreforweb:' + openid)
        if score_cache:
            score_info = ast.literal_eval(score_cache[b'score_info'].decode())
            real_name = score_cache[b'real_name'].decode('utf-8')
            return render_template('wechat/score.html',
                    real_name = real_name,
                    school_term = score_cache[b'school_term'].decode('utf-8'),
                    score_info = score_info,
                    update_time = score_cache[b'update_time'].decode('utf-8'),
                    baidu_analyics= current_app.config['BAIDU_ANALYTICS'],
                    jsapi = Markup(jsapi)
                    )
        else:
            abort(404)
    else:
        abort(404)


@wechat.route('/auth-library/<openid>/result', methods=['GET'])
def auth_library_result(openid=None):
    """查询借书卡绑定结果"""
    if is_user_exists(openid):
        redis_prefix = 'wechat:user:auth:library:'
        errmsg = redis.get(redis_prefix + openid)
        if errmsg:
            redis.delete(redis_prefix + openid)
            return jsonify({'errmsg': errmsg})
        else:
            abort(404)
    else:
        abort(404)


    """ 修改用户分组 """
    if form.validate_on_submit():
        groupemp = []
        groupemp_list = form.group.data.split(',')
        for t in groupemp_list:
            tag = Group.query.filter_by(name=t).first()
            if tag is None:
                tag = Group()
                tag.name = t
            groupemp.append(tag)
        user.user_group = groupemp
        user.save()
        return redirect(url_for('wechat.user'))
    value = ",".join([i.name for i in user.user_group])
    return render_template('wechat/editgroup.html',form=form, user=user, value=value)


#  不用oauth授权的话, 只能传openid参数了
#  @wechat.route('/setting/<openid>', methods=['GET', 'POST'])
#  @oauth_request
@wechat.route('/setting/<openid>', methods=['GET', 'POST'])
def setting(openid=None):
    user = WechatUser.query.filter_by(openid=openid).first()
    if request.method == 'POST':
        #  只是保存了用户的设置的一个列表
        setting_list = request.form.getlist('setting')

        #  根据设置给用户分组
        for i in setting_list:
            group = Group.query.filter_by(name=i).first()
            if group not in user.user_group:
                if group is None:
                    new_group = Group()
                    new_group.name = i
                    user.user_group.append(new_group)
                else:
                    user.user_group.append(group)
            user.update()

        #  用户去掉某个选择的时候, 就是比对数据库的user_setting和从网页传回来的setting_list
        if user.user_setting:
            user_setting_list = json.loads(user.user_setting)
            for i in user_setting_list:
                if i not in setting_list:
                    delete_group = Group.query.filter_by(name=i).first()
                    user.user_group.remove(delete_group)
        user.user_setting = json.dumps(setting_list)
        user.update()
        return render_template('wechat/setting_success.html')
    else:
        if user.user_setting:
            setting_list = json.loads(user.user_setting)
            setting_list = ','.join(setting_list)
        else:
            setting_list = []
        return render_template('wechat/setting.html', values = setting_list)


@wechat.route('/phonenumber', methods=['GET'])
def phone_number():
    """ 回复常用电话 """
    return render_template('wechat/phone_number.html')


@wechat.route('/user')
@login_required
def user():
    """ 用户列表 """
    users = WechatUser.query.all()
    groups = Group.query.order_by(Group.id)[::-1] # 所有标签返回的是一个元组
    #  FIXME 该分组下用户数为0, 删除这个分组
    for c in groups:
        p = c.wechatusers.all()
        if len(p) == 0:
            db.session.delete(c)
    return render_template('wechat/user.html', users=users)


@wechat.route('/editgroup/<int:id>', methods = ['GET','POST'])
@login_required
@admin_required
def editgroup(id=0):
    """ 修改用户分组 """
    form = GroupForm()
    user = WechatUser.query.get_or_404(id)
    if form.validate_on_submit():
        groupemp = []
        groupemp_list = form.group.data.split(',')
        for t in groupemp_list:
            tag = Group.query.filter_by(name=t).first()
            if tag is None:
                tag = Group()
                tag.name = t
            groupemp.append(tag)
        user.user_group = groupemp
        user.save()
        return redirect(url_for('wechat.user'))
    value = ",".join([i.name for i in user.user_group])
    return render_template('wechat/editgroup.html',form=form, user=user, value=value)


@wechat.route('/groups/<name>', methods=['GET', 'POST'])
def group(name):
    group = Group.query.filter_by(name = name).first() # name对应的标签对象
    page_index = request.args.get('page', 1, type=int)
    pagination = group.wechatusers.order_by(WechatUser.id.desc()).paginate( page_index, per_page = 8, error_out=False)
    users = pagination.items
    return render_template("wechat/groups.html", name = name, users = users, group = group, pagination=pagination)


@wechat.route('/push', methods=['GET', 'POST'])
@login_required
@admin_required
def push():
    """ 推送图文消息"""
    newsform = NewsForm()
    form = TextForm()
    wechat = init_wechat_sdk()
    client = wechat['client']
    pushnews = Pushnews(author_id = current_user.id)
    if request.method == 'POST':
        #  把推送保存到数据库, 并发送微信
        title = newsform.title.data
        body = newsform.body.data
        to_group = Group.query.get(newsform.group.data)
        to_user = []
        to_user_id = []
        for u in to_group.wechatusers:
            to_user.append(u.openid)
            to_user_id.append(u.id)

        try:
            #  添加到图文素材库
            pushnews.title = title
            pushnews.body = body
            pushnews.to_group = to_group
            pushnews.to_confirmed = json.dumps(to_user_id)
            pushnews.save()
            body_html=pushnews.body_html
            #  更新最新推送的通知缓存
            articles= [{
                'title':title,
                'show_cover_pic' : 0,
                'content':body_html, # 看看是否需要处理html
                'author':current_user.name,
                'thumb_media_id':current_app.config['NEWS_THUMB_MEDIA_ID'],
                'digest':current_app.config['NEWS_DIGEST'],
                'content_source_url':current_app.config['NEWS_CONTENT_SOURCE_URL'],
                'need_open_comment' : '1',
                'only_fans_can_comment' : '1'
            }]
            res = client.material.add_articles(articles)
            #  XXX, 为什么没有保存到数据库, 但却发送成功了
            media_id = res['media_id']

app/templates/wechat/groups.html
{% extends "base.html" %}
{% from "bootstrap/pagination.html" import render_pagination %}

{% block page_content %}
<!DOCTYPE html>  
<html lang="zh-CN">  

	<head>  
		<meta charset="utf-8">  
		<meta http-equiv="X-UA-Compatible" content="IE=edge">  
		<meta name="viewport" content="width=device-width, initial-scale=1">  
		<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->  
		<title>表格</title>  
		<meta name="keywords" content="表格">  
		<meta name="description" content="这真的是一个表格" />  
		<meta name="HandheldFriendly" content="True" />  
		<link rel="shortcut icon" href="img/favicon.ico">  
	</head>  

	<body>
		<div class="panel-group">
			<div class="panel panel-primary">
				<div class="panel-heading">用户列表 </div>
				<table class="table table-bordered table-hover">
					<thead>
						<tr class="success">
							<th>操作</th>
							<th>真实姓名</th>
							<th>班级名称</th>
							<th>分组</th>
							<th>昵称</th>
							<th>城市</th>
							<th>OpenId</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							{% for user in users%}
              <td>
                <a href="{{ url_for('wechat.editgroup', id=user.id) }}" style="float:right">
                  <button class= "btn btn-sm" data-toggle = "modal" data-target = "#update">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"> 分组</button>
                  </a>
							</td>
							<td>{{user.realname}}</td>
							<td>{{user.classname}}</td>

							<td>
								{% for group in user.user_group%}
                <a href="{{ url_for('wechat.group', name = group.name) }}">
                  <button class= "btn btn-sm" data-toggle = "modal" data-target = "#update">
                    <span class="glyphicon glyphicon-tag" aria-hidden="true">{{group.name}}</button>
                </a>
								&nbsp &nbsp
								{% endfor %}
							</td>
							<td>{{user.nickname}}</td>
							<td>{{user.city}}</td>
							<td>{{user.openid}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div><!-- end of panel -->
		</div>



		<script>
			$(function(){
				//触发模态框的同时调用此方法  
				function editInfo(obj) {  
					var id = $(obj).attr("id");  
					//获取表格中的一行数据  
					var stuno = document.getElementById("table").rows[id].cells[0].innerText;  
					var pass = document.getElementById("table").rows[id].cells[1].innerText;  
					var name = document.getElementById("table").rows[id].cells[2].innerText;  
					var sex = document.getElementById("table").rows[id].cells[3].innerText;  
					//向模态框中传值  
					$('#stuno').val(stuno);  
					$('#pass').val(pass);  
					$('#stuname').val(name);  
					if (sex == '女') {  
						document.getElementById('women').checked = true;  
					} else {  
						document.getElementById('man').checked = true;  
					}  
						$('#update').modal('show');  
					}  
					//提交更改  
					function update() {  
						//获取模态框数据  
						var stuno = $('#stuno').val();  
						var pass = $('#pass').val();  
						var name = $('#stuname').val();  
						var sex = $('input:radio[name="sex"]:checked').val();  
						$.ajax({  
							type: "post",  
							url: "update.do",  
							data: "stuno=" + stuno + "&pass=" + pass + "&name=" + name + "&sex=" + sex,  
							dataType: 'html',  
							contentType: "application/x-www-form-urlencoded; charset=utf-8",  
							success: function(result) {  
								//location.reload();  
							}  
						});  
					}  

					function initTableCheckbox() {  
						var $thr = $('table thead tr');  
						var $checkAllTh = $('<th><input type="checkbox" id="checkAll" name="checkAll" /></th>');  
						/*将全选/反选复选框添加到表头最前，即增加一列*/  
						$thr.prepend($checkAllTh);  
						/*“全选/反选”复选框*/  
						var $checkAll = $thr.find('input');  
						$checkAll.click(function(event){  
							/*将所有行的选中状态设成全选框的选中状态*/  
							$tbr.find('input').prop('checked',$(this).prop('checked'));  
							/*并调整所有选中行的CSS样式*/  
							if ($(this).prop('checked')) {  
								$tbr.find('input').parent().parent().addClass('warning');  
							} else{  
								$tbr.find('input').parent().parent().removeClass('warning');  
							}  
							/*阻止向上冒泡，以防再次触发点击操作*/  
							event.stopPropagation();  
						});  
						/*点击全选框所在单元格时也触发全选框的点击操作*/  
						$checkAllTh.click(function(){  
							$(this).find('input').click();  
						});  
						var $tbr = $('table tbody tr');  
						var $checkItemTd = $('<td><input type="checkbox" name="checkItem" /></td>');  
						/*每一行都在最前面插入一个选中复选框的单元格*/  
						$tbr.prepend($checkItemTd);  
						/*点击每一行的选中复选框时*/  
						$tbr.find('input').click(function(event){  
							/*调整选中行的CSS样式*/  
							$(this).parent().parent().toggleClass('warning');  
							/*如果已经被选中行的行数等于表格的数据行数，将全选框设为选中状态，否则设为未选中状态*/  
							$checkAll.prop('checked',$tbr.find('input:checked').length == $tbr.length ? true : false);  
							/*阻止向上冒泡，以防再次触发点击操作*/  
							event.stopPropagation();  
						});  
						/*点击每一行时也触发该行的选中操作*/  
						$tbr.click(function(){  
							$(this).find('input').click();  
						});  
					}  
					initTableCheckbox();  
				});
			</script>
		</body>
	</html>

	{% endblock %}

app/templates/wechat/user.html
{% extends "base.html" %}

{% block page_content %}
<!DOCTYPE html>  
<html lang="zh-CN">  

  <head>  
    <meta charset="utf-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">  
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->  
    <title>表格</title>  
    <meta name="keywords" content="表格">  
    <meta name="description" content="这真的是一个表格" />  
    <meta name="HandheldFriendly" content="True" />  
    <link rel="shortcut icon" href="img/favicon.ico">  
  </head>  

  <body>
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">用户列表 </div>
        <!-- <table class="table table-bordered table-hover"> -->
        <table class="table table-bordered table-hover sortable">
          <thead>
            <tr class="success">
              <th>操作</th>
              <th>真实姓名</th>
              <th>班级名称</th>
              <th>分组</th>
              <th>昵称</th>
              <th>城市</th>
              <th>OpenId</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              {% for user in users%}
              <td>
                <a href="{{ url_for('wechat.editgroup', id=user.id) }}" style="float:right">
                  <button class= "btn btn-sm" data-toggle = "modal" data-target = "#update">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"> 分组</button>
                  </a>
                </td>
                <td>{{user.realname}}</td>
                <td>{{user.classname}}</td>

                <td>
                  {% for group in user.user_group%}
                <a href="{{ url_for('wechat.group', name = group.name) }}">
                  <button class= "btn btn-sm" data-toggle = "modal" data-target = "#update">
                    <span class="glyphicon glyphicon-tag" aria-hidden="true">{{group.name}}</button>
                </a>
                  &nbsp &nbsp
                  {% endfor %}
                </td>
                <td>{{user.nickname}}</td>
                <td>{{user.city}}</td>
                <td>{{user.openid}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>



        </div><!-- end of panel -->
      </div>



      <!-- jQuery1.11.3 (necessary for Bo otstrap's JavaScript plugins) -->
      <script src="js/jquery-1.11.3.min.js "></script>
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="js/bootstrap.min.js "></script>
      <script>
        $(function(){
          //触发模态框的同时调用此方法  
          function editInfo(obj) {  
            var id = $(obj).attr("id");  
            //获取表格中的一行数据  
            var stuno = document.getElementById("table").rows[id].cells[0].innerText;  
            var pass = document.getElementById("table").rows[id].cells[1].innerText;  
            var name = document.getElementById("table").rows[id].cells[2].innerText;  
            var sex = document.getElementById("table").rows[id].cells[3].innerText;  
            //向模态框中传值  
            $('#stuno').val(stuno);  
            $('#pass').val(pass);  
            $('#stuname').val(name);  
            if (sex == '女') {  
              document.getElementById('women').checked = true;  
            } else {  
              document.getElementById('man').checked = true;  
            }  
            $('#update').modal('show');  
          }  
          //提交更改  
          function update() {  
            //获取模态框数据  
            var stuno = $('#stuno').val();  
            var pass = $('#pass').val();  
            var name = $('#stuname').val();  
            var sex = $('input:radio[name="sex"]:checked').val();  
            $.ajax({  
              type: "post",  
              url: "update.do",  
              data: "stuno=" + stuno + "&pass=" + pass + "&name=" + name + "&sex=" + sex,  
              dataType: 'html',  
              contentType: "application/x-www-form-urlencoded; charset=utf-8",  
              success: function(result) {  
                //location.reload();  
              }  
            });  
          }  

          function initTableCheckbox() {  
            var $thr = $('table thead tr');  
            var $checkAllTh = $('<th><input type="checkbox" id="checkAll" name="checkAll" /></th>');  
            /*将全选/反选复选框添加到表头最前，即增加一列*/  
            $thr.prepend($checkAllTh);  
            /*“全选/反选”复选框*/  
            var $checkAll = $thr.find('input');  
            $checkAll.click(function(event){  
              /*将所有行的选中状态设成全选框的选中状态*/  
              $tbr.find('input').prop('checked',$(this).prop('checked'));  
              /*并调整所有选中行的CSS样式*/  
              if ($(this).prop('checked')) {  
                $tbr.find('input').parent().parent().addClass('warning');  
              } else{  
                $tbr.find('input').parent().parent().removeClass('warning');  
              }  
              /*阻止向上冒泡，以防再次触发点击操作*/  
              event.stopPropagation();  
            });  
            /*点击全选框所在单元格时也触发全选框的点击操作*/  
            $checkAllTh.click(function(){  
              $(this).find('input').click();  
            });  
            var $tbr = $('table tbody tr');  
            var $checkItemTd = $('<td><input type="checkbox" name="checkItem" /></td>');  
            /*每一行都在最前面插入一个选中复选框的单元格*/  
            $tbr.prepend($checkItemTd);  
            /*点击每一行的选中复选框时*/  
            $tbr.find('input').click(function(event){  
              /*调整选中行的CSS样式*/  
              $(this).parent().parent().toggleClass('warning');  
              /*如果已经被选中行的行数等于表格的数据行数，将全选框设为选中状态，否则设为未选中状态*/  
              $checkAll.prop('checked',$tbr.find('input:checked').length == $tbr.length ? true : false);  
              /*阻止向上冒泡，以防再次触发点击操作*/  
              event.stopPropagation();  
            });  
            /*点击每一行时也触发该行的选中操作*/  
            $tbr.click(function(){  
              $(this).find('input').click();  
            });  
          }  
          initTableCheckbox();  
        });
      </script>
    </body>
  </html>

  {% endblock %}